go/examples/policiesCrud/main.go, go/service/policies/api_op_DeletePolicy.go
This PR adds examples of policy management in the Golang client.
=> docs: add policies example for golang client

go/service/assets/api_op_CreateAsset.go, go/service/assets/api_op_DeleteAsset.go, go/service/assets/api_op_DeleteAsset_test.go, go/service/assets/api_op_GetAsset.go, go/service/assets/api_op_ListAssets.go
Handle http responses when unhappy path.
I haven't written any tests yet. One way to test, for now, is to modify the examples to add values that cause errors ( missing fields, non-existant ids...)
---
=> feat(go): handle http error responses assets api

src/controllers/management-controller.ts, src/entities/asset.ts, src/entities/data-address.ts, tests/controllers/management.test.ts
This is an attempt to implement #22 
- `yarn`
- `yarn test`
---
This is following the same principle we used in developing  `getAsset` in the EDC client
=> feat: get asset data address

src/controllers/management-controller.ts, tests/controllers/management.test.ts
This PR is an attempt to resolve #29 
Run `yarn test` and have all the tests running successfully
---
Added a query to the request and changed it from **GET** to **POST** following the connector's management api specs.
=> feat: add query to listing assets

src/entities/contract-definition.ts
This PR resolves #32 
Everything should be working as expected
---
<!--
=> fix: update contract definition object with missing properties

.github/dependabot.yml, connector/build.gradle.kts, connector/gradle/libs.versions.toml, package.json
Add dependabot configuration for these ecosystems:
- github_actions
- gradle
- yarn
To keep dependencies updated
- add some missing metadata from the `package.json` file.
Closes #41 
Closes #44
=> build: configure dependabot

src/controllers/management-controller.ts, tests/controllers/management.test.ts
=> feat: update a contract definition

src/controllers/management-controllers/contract-agreement-controller.ts, tests/controllers/management-tests/contract-agreements.test.ts
Support `/contractagreements/v2/negotiation`:
https://app.swaggerhub.com/apis/eclipse-edc-bot/management-api/0.2.1#/Contract%20Agreement/getNegotiationByAgreementId
Closes #83
=> feat: support `/contractagreements/{id}/negotiation` endpoint

src/entities/criterion.ts, tests/controllers/management-tests/contract-definitions.test.ts
Fix `Criterion` getters definition
Closes #94
=> fix: fix Criterion getters

src/controllers/management-controllers/asset-controller.ts, src/controllers/management-controllers/catalog-controller.ts, src/controllers/management-controllers/contract-agreement-controller.ts, src/controllers/management-controllers/contract-defintion-controller.ts, src/controllers/management-controllers/contract-negotiation-controller.ts, src/controllers/management-controllers/dataplane-controller.ts, src/controllers/management-controllers/policy-defintion-controller.ts, src/controllers/management-controllers/transfer-process-controller.ts, src/entities/context.ts, src/entities/jsonld.ts, src/entities/transfer-process.ts, tests/controllers/management-tests/transfer-processes.test.ts, tests/test-utils.ts
Adding missing functionalities to the transfer process controller:
- `get`
- `terminate`
- `deprovision`
complete features
- passed the edc namespace as `@vocab` for every request
Closes #131
=> feat: implement missing transfer process functionalities

src/entities/catalog.ts, tests/test-utils.ts
Remove `assetId` method from `Offer`
To align with DSP specs
Closes #159
=> feat: remove assetId from Offer

connector/build.gradle.kts, connector/gradle/libs.versions.toml, src/entities/jsonld.ts, tests/controllers/management-tests/catalog.test.ts, tests/controllers/management-tests/contract-negotiations.test.ts, tests/controllers/management-tests/transfer-processes.test.ts
Bump EDC to 0.5.0
just a minimum effort on the json-ld deserialization needed, tests have been changed [to work around a EDC flaw introduced with 0.5.0](https://github.com/eclipse-edc/Connector/issues/3814)
=> build(deps): bump EDC to 0.5.0

package.json, tests/controllers/management-tests/edrs.test.ts, yarn.lock
Bump jest to 29.7.0
Apparently Dependabot didn't consider doing that
=> build: Bump jest to 29.7.0

.github/workflows/publish-npm.yml
=> build: checkout main last commit when publishing

README.md, connector/build.gradle.kts, connector/gradle/libs.versions.toml
=> build(deps): bump EDC to 0.7.1

README.md, connector/gradle/libs.versions.toml, pretest/edc-openapi.js, src/controllers/management-controllers/asset-controller.ts, src/controllers/management-controllers/catalog-controller.ts, src/controllers/management-controllers/contract-agreement-controller.ts, src/controllers/management-controllers/contract-defintion-controller.ts, src/controllers/management-controllers/contract-negotiation-controller.ts, src/controllers/management-controllers/dataplane-controller.ts, src/controllers/management-controllers/edr-controller.ts, src/controllers/management-controllers/policy-defintion-controller.ts, src/controllers/management-controllers/secret-controller.ts, src/controllers/management-controllers/transfer-process-controller.ts
switch to [management api v3](https://eclipse-edc.github.io/Connector/openapi/management-api/)
closes: #262
=> feat: switch to management v3

.github/workflows/test.yml, connector/build.gradle.kts, connector/gradle/libs.versions.toml, src/entities/catalog.ts, src/entities/jsonld.ts
=> build(deps): bump EDC to 0.9.0

src/controllers/identity-controllers/participant-controllers/participant-controller.ts, src/controllers/identity-controllers/participant-controllers/participant-verifiable-credentials-controller.ts, src/controllers/identity-controllers/verifiable-credentials-controller.ts, src/entities/policy/policy.ts, src/entities/policy/prohibition.ts, src/entities/verifiable-credentials.ts, src/facades/identity.ts, tests/controllers/identity-tests/verifiableCredential.test.ts
This PR adds the verifiable credentials controller for identity hub.
```
yarn test
```
=> feat: verifiable credentials controller

connector/Dockerfile, connector/build.gradle.kts, connector/gradle/libs.versions.toml, connector/src/main/java/io/thinkit/client/extension/DemoTargetNodeDirectory.java, package-lock.json, yarn.lock
bump edc to version 0.13.0
adjust version for edc-transfer-pull-http-dynamic-receiver
implement missing method for TargetNodeDirectory
Run unit/integration tests
Close #447
=> bump edc to version 0.13.0

tests/controllers/identity-tests/verifiableCredential.test.ts
=> ci: fix broken test
